#!/bin/bash

# Use this script for building examples and as a guide for integrating elm-d3
# into other projects. Run it from anywhere and it will print out script flags
# the elm compiler can use to include d3 and the elm-d3 runtime into generated
# html.
#
# This script assumes that it lives in its original location in an elm-d3
# repository that has already been built using `make`. It will point to the
# elm-d3 runtime file with that repository. You can override this using the
# ELMD3 environment variable.
#
# By default this will point the elm compiler to the latest 3.x release of d3
# on the Internet. You can override this using the D3 environment variable.
#
# Be careful with trailing slaces in the SOURCE and PREFIX environment
# variables. This script uses them as given, and doesn't try to clean up
# extraneous slashes, which may bite you when you're trying to generate paths
# for a web server.

if [ -z $ELMD3 ]; then
    ELMD3=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
fi

if [ -z $D3 ]; then
    D3="http://d3js.org/d3.v3.min.js"
fi

# Here's an example:
#
#   $ elm --make `./scripts/build-flags` examples/Boxes.elm
#
# If you run this in the root of the elm-d3 source tree, it will build the
# Boxes example. You can then open up the generalted html in a browser without
# worring about paths or spinning up a temporary server.

echo "--script $D3 --script file://$ELMD3/elm-d3.runtime.js"
