#!/bin/bash

# Use this script to include stylesheets in your elm-d3 projects. Specify the
# stylesheets you want to include as command-line arguments. This script will
# embed those stylesheets in a JavaScript file, and print out the script flags
# the elm compiler can use to include that JavaScript in generated html.

TEMPFILE=`mktemp style-XXX`
trap "rm $TEMPFILE 2>/dev/null || true" exit

cat << EOF > $TEMPFILE
var style = document.querySelector('head').appendChild(document.createElement('style'));
style.innerText = "`cat $@ | sed -e 's/\\$//' -e 's/\\"/\\\\"/g' | tr -d '\n'`";
EOF

mkdir -p `pwd`/build
mv $TEMPFILE `pwd`/build/$TEMPFILE.js

echo --script file://`pwd`/build/$TEMPFILE.js
